#+TITLE: My Paper
#+AUTHOR: Jane Doe
#+DATE: 1. 2. 3456
#+OPTIONS:   H:5 num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+LaTeX_CLASS: memoir
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,times,12pt,listings-bw,microtype]
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont{Times New Roman}


* Chapter the first

Ελληνικά. 

Jay L. Garfield: Well, the answer to this is rather roundabout, and reflects more my own indecision and the randomness of life than anything else. And it is a bit embarrassing. When I went to college I knew what I wanted to study, and what career I wanted to pursue. I wanted to study psychology in order to become a clinical psychologist. So, preparing for my first semester at Oberlin, I chose a bunch of psychology classes, but I had to choose one class outside of psychology. Looking through the catalogue, nothing else interested me. I was young and stupid. So, I did what so many other undergraduates do: I closed my eyes, opened the catalogue, and promised myself to take the first class my finger fell on that fit my schedule. It was a philosophy class. I groaned, but I told myself that I could always drop it after a few classes if it was as boring as it promised to be. Of course, it was a superb class, taught by the late Norman Care. And by the time we opened Hume’s Treatise I was hooked. The attack on the self, on a real causal relation, on universals, and the defense of custom as a foundation not only of social organisation but of ontology and meaning stunned me. So, I decided to double major – philosophy and psychology, but promised myself that I would do honors and graduate work in psychology. The time came for choosing an honors thesis. I was having too much fun in both disciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.


** Underthapter with a quote

The quote is here: sciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.

#+BEGIN_QUOTE
Jay L. Garfield: Well, the answer to this is rather roundabout, and reflects more my own indecision and the randomness of life than anything else. And it is a bit embarrassing. When I went to college I knew what I wanted to study, and what career I wanted to pursue. I wanted to study psychology in order to become a clinical psychologist. So, preparing for my first semester at Oberlin, I chose a bunch of psychology classes, but I had to choose one class outside of psychology. Looking through the catalogue, nothing else interested me. I was young and stupid. So, I did what so many other undergraduates do: I closed my eyes, opened the catalogue, and promised myself to take the first class my finger fell on that fit my schedule. It was a philosophy class. I groaned, but I told myself that I could always drop it after a few classes if it was as boring as it promised to be. Of course, it was a superb class, taught by the late Norman Care. And by the time we opened Hume’s Treatise I was hooked. The attack on the self, on a real causal relation, on universals, and the defense of custom as a foundation not only of social organisation but of ontology and meaning stunned me. So, I decided to double major – philosophy and psychology, but promised myself that I would do honors and graduate work in psychology. The time came for choosing an honors thesis. I was having too much fun in both disciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.
#+END_QUOTE

** Underthapter with a quote

The quote is here: sciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.

#+BEGIN_QUOTE
Jay L. Garfield: Well, the answer to this is rather roundabout, and reflects more my own indecision and the randomness of life than anything else. And it is a bit embarrassing. When I went to college I knew what I wanted to study, and what career I wanted to pursue. I wanted to study psychology in order to become a clinical psychologist. So, preparing for my first semester at Oberlin, I chose a bunch of psychology classes, but I had to choose one class outside of psychology. Looking through the catalogue, nothing else interested me. I was young and stupid. So, I did what so many other undergraduates do: I closed my eyes, opened the catalogue, and promised myself to take the first class my finger fell on that fit my schedule. It was a philosophy class. I groaned, but I told myself that I could always drop it after a few classes if it was as boring as it promised to be. Of course, it was a superb class, taught by the late Norman Care. And by the time we opened Hume’s Treatise I was hooked. The attack on the self, on a real causal relation, on universals, and the defense of custom as a foundation not only of social organisation but of ontology and meaning stunned me. So, I decided to double major – philosophy and psychology, but promised myself that I would do honors and graduate work in psychology. The time came for choosing an honors thesis. I was having too much fun in both disciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.
#+END_QUOTE

* Underthapter with a quote

The quote is here: sciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.

#+BEGIN_QUOTE
Jay L. Garfield: Well, the answer to this is rather roundabout, and reflects more my own indecision and the randomness of life than anything else. And it is a bit embarrassing. When I went to college I knew what I wanted to study, and what career I wanted to pursue. I wanted to study psychology in order to become a clinical psychologist. So, preparing for my first semester at Oberlin, I chose a bunch of psychology classes, but I had to choose one class outside of psychology. Looking through the catalogue, nothing else interested me. I was young and stupid. So, I did what so many other undergraduates do: I closed my eyes, opened the catalogue, and promised myself to take the first class my finger fell on that fit my schedule. It was a philosophy class. I groaned, but I told myself that I could always drop it after a few classes if it was as boring as it promised to be. Of course, it was a superb class, taught by the late Norman Care. And by the time we opened Hume’s Treatise I was hooked. The attack on the self, on a real causal relation, on universals, and the defense of custom as a foundation not only of social organisation but of ontology and meaning stunned me. So, I decided to double major – philosophy and psychology, but promised myself that I would do honors and graduate work in psychology. The time came for choosing an honors thesis. I was having too much fun in both disciplines, so I decided to write two honors theses, but to go to graduate school in psychology. So I wrote a thesis on the mysticism in Wittgenstein’s Tractatus, a text I saw as taking Humean insights one step deeper, as well as a thesis in psychology on attention and behaviour modification. And I provided myself an important safety net. I realised that it was hard to get into graduate school in psychology, and so I applied to graduate school in philosophy as a backup. So then, a terrible thing happened. I was accepted both into graduate school in psychology and into graduate school in philosophy. The philosophy letter, however, arrived with an ominous warning from the APA advising any prospective graduate student in philosophy not to attend, as there were no jobs to be had on graduation. That letter decided things for me. After all, if I were to go to graduate school in psychology, I would immediately have a job, and would never study philosophy again; but I were to go to graduate school in philosophy, I would not get a job, and could then do a second PhD in psychology and settle down to a happy life, having studied both of the subjects I loved. So I went to graduate school in philosophy so as not to get a job. But I failed. I did secure a position teaching philosophy – happily, in a cognitive science program – have loved every minute of it, and never looked back.
#+END_QUOTE
